In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import colors, cm
from pyspoc.calculator import Calculator
import networkx as nx
from causallearn.search.ConstraintBased.PC import pc
from causallearn.utils.GraphUtils import GraphUtils
from causallearn.graph.GeneralGraph import GeneralGraph
from pathlib import Path
import os

In [14]:
project_root = Path('./').resolve().parents[2]
base_dir = os.path.join(project_root, 'mastersResearch_Jun_Sept2025', 'causalDiscovery_J', 'motivationAnalysis')
for dag_number in [1,2]:
    print(os.path.join(base_dir, f'motivation_dag_{dag_number}.csv'))
    meta_file = os.path.join(base_dir, f'motivation_dag_{dag_number}.csv')
    meta_df = pd.read_csv(meta_file)
    data = meta_df.to_numpy()

    # default parameters
    cg = pc(data)

    pyd = GraphUtils.to_pydot(cg.G)
    pyd.write_png(f'discovered_dag_{dag_number}.png')

    print(cg.G.graph)

    # visualization using pydot
    # cg.draw_pydot_graph()

/Users/joshparchure/Documents/1AugClonedRepo/py-spoc/working_analyses/mastersResearch_Jun_Sept2025/causalDiscovery_J/motivationAnalysis/motivation_dag_1.csv


  0%|          | 0/3 [00:00<?, ?it/s]

[[ 0  0  0]
 [ 0  0 -1]
 [ 0 -1  0]]
/Users/joshparchure/Documents/1AugClonedRepo/py-spoc/working_analyses/mastersResearch_Jun_Sept2025/causalDiscovery_J/motivationAnalysis/motivation_dag_2.csv


  0%|          | 0/3 [00:00<?, ?it/s]

[[ 0 -1 -1]
 [-1  0 -1]
 [-1 -1  0]]


In [3]:
!conda list

# packages in environment at /opt/anaconda3/envs/pyspoc_env_5Aug:
#
# Name                    Version                   Build  Channel
anyio                     4.9.0              pyh29332c3_0    conda-forge
appnope                   0.1.4              pyhd8ed1ab_1    conda-forge
argon2-cffi               25.1.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0          py312h024a12e_5    conda-forge
arrow                     1.3.0              pyhd8ed1ab_1    conda-forge
asttokens                 3.0.0              pyhd8ed1ab_1    conda-forge
async-lru                 2.0.5              pyh29332c3_0    conda-forge
attrs                     25.3.0             pyh71513ae_0    conda-forge
autograd                  1.8.0                    pypi_0    pypi
aws-c-auth                0.9.0               hb5b73c5_15    conda-forge
aws-c-cal                 0.9.2                h03444cf_0    conda-forge
aws-c-common              0.12.3               h5505292_0    conda-fo